fix: apply contribution fee per mint
PartyDAO/party-protocol pull request #297
Opened 2023-09-09 02:29 UTC by 0xble

2023-09-09 20:57 UTC, arr00 requested changes

2023-09-09 20:57 UTC, arr00 commented on test/crowdfund/ContributionRouterIntegration.t.sol
> +    constructor() {
Should use the `setUp` function instead of constructor

2023-09-09 20:57 UTC, arr00 commented on test/crowdfund/ContributionRouterIntegration.t.sol
> +        uint256 numOfMints;
num mints never set

2023-09-09 22:15 UTC, 0xble commented on test/crowdfund/ContributionRouterIntegration.t.sol
> +        uint256 numOfMints;
Oof. Good catch

2023-09-10 13:41 UTC, arr00 commented on contracts/crowdfund/ContributionRouter.sol
> +        } else if (msg.sig == Crowdfund.batchContributeFor.selector) {
Given that we don't plan on using this functionality, I don’t think it’s worth adding.

2023-09-11 18:10 UTC, merged