deploy: update deploy constants and verify
PartyDAO/party-protocol pull request #387
Opened 2024-03-26 19:46 UTC by 0xble

## Motivation

## Solution

2024-04-07 23:12 UTC, arr00 requested changes
`tokenDistributorV3` changed to be incorrect?

2024-05-08 16:02 UTC, arr00 commented
@0xble should this be closed?

2024-05-08 16:03 UTC, 0xble commented
> @0xble should this be closed?

There's an update to the `verify.ts` that's important, but I'll undo the change to addresses.

2024-05-08 17:15 UTC, arr00 approved these changes

2024-05-08 17:15 UTC, merged